export const CHECK_LOGIN="CHECK_LOGIN";
export const REGISTER="REGISTER";
export const LOGIN="LOGIN";
export const LOGOUT="LOGOUT";
export const FORGET_PASSWORD="FORGET_PASSWORD";
export const RESET_PASSWORD="RESET_PASSWORD";

export const CHECK_LOGIN_FAIL="CHECK_LOGIN_FAIL";
export const REGISTER_FAIL="REGISTER_FAIL";
export const LOGIN_FAIL="LOGIN_FAIL";
export const FORGET_PASSWORD_FAIL="FORGET_PASSWORD_FAIL";
export const RESET_PASSWORD_FAIL="RESET_PASSWORD_FAIL";